name: Update facade if needed

on:
  push:
    paths:
      - "**.php"
      - ".github/workflows/update-facade.yml"

permissions:
  contents: write

jobs:
  update-facade:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v4

      - name: Update facade
        run: vendor/bin/testbench autodoc:facades src/Facades

      - name: Patch enum default values in facade
        run: php patch-facade-docblock.php

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Update facade
